### ISSUE TITLE
BooleanNetwork.instantiate - infer_valid_graph by default

### ISSUE THREAD

**Issue by smijeva** [sybila/biodivine-aeon-py#23]
Currently, when an `instantiate` method is called upon BooleanNetwork (in any version), the Boolean network is still referencing the original regulatory network. This is a counter-intuitive behavior, since the former regulatory network might contain numerous extra (unobservable) regulations. An extra call of `infer_valid_graph` is going to be needed in the majority of the use cases of this method.

An improved behavior would be to introduce an extra optional parameter to the `instantiate` method (e.g. infer_regularizatin=True), which will make the method call the  infer_valid_graph right upon instantiation. If a former regulatory network is desired to be preserved, this parameter then can be set to False.

**Comment by daemontus** [comment]
Fixed on `main` now (see 9cb317623dac5e1292e1927296781daaacf9f1cc). Will be available in the next release. Default for the new parameter is `infer_regulations=False` to retain backwards compatibility.
